set nocompatible

set backspace=indent,eol,start

set modelines=0

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set textwidth=70
set fo=crq
set autoindent

set ruler
set nowrap

set laststatus=2
set encoding=utf-8

set showmatch
set showcmd

set wildmode=list:longest,full

set incsearch
set infercase
set ignorecase
set smartcase
set hlsearch

set listchars=eol:$,tab:>-,trail:-,extends:>,precedes:<

filetype plugin on
filetype indent on

syntax enable
highlight clear SignColumn
highlight RedundantSpaces ctermbg=red
match RedundantSpaces /\s\+\%#\@<!$/

set number
set scrolloff=5
set hidden

set nobackup
set noswapfile

set viminfo=

set modeline

let g:netrw_liststyle=3
let g:netrw_banner=0
let g:netrw_dirhistmax=0

set pastetoggle=<F2>

set laststatus=1

set title

autocmd FileType go setlocal noexpandtab
autocmd FileType gitconfig setlocal noexpandtab

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fsSLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugins')

Plug 'chriskempson/base16-vim'
Plug 'kchmck/vim-coffee-script'
if executable('go')
  Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }
endif

call plug#end()

if executable('go')
  let g:go_fmt_command='gopls'
  let g:go_gopls_gofumpt=1
  let g:go_auto_type_info=1
  set completeopt-=preview
endif

set termguicolors
colorscheme base16-tomorrow-night
