set nocompatible

set backspace=indent,eol,start

set modelines=0

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set textwidth=70
set fo=crq
set autoindent

set ruler
set nowrap

set laststatus=2
set encoding=utf-8

set showmatch
set showcmd

set wildmode=list:longest,full

set incsearch
set infercase
set ignorecase
set smartcase
set hlsearch

set listchars=eol:$,tab:>-,trail:-,extends:>,precedes:<

filetype plugin on
filetype indent on

syntax enable
highlight clear SignColumn
highlight RedundantSpaces ctermbg=red
match RedundantSpaces /\s\+\%#\@<!$/

set number
set scrolloff=5
set hidden

set nobackup
set noswapfile

set viminfo=

set modeline

" NERDtree like setup with netrw.
" See https://shapeshed.com/vim-netrw/.
let g:netrw_dirhistmax=0
let g:netrw_banner=0
let g:netrw_liststyle=3
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_winsize=15
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * nmap <buffer> <F5> :Vexplore<CR>
augroup END
autocmd FileType netrw setl bufhidden=delete

" Automatically quit vim if netrw is last and only buffer.
augroup netrwClose
  autocmd!
  autocmd WinEnter * if winnr('$') == 1 && getbufvar(winbufnr(winnr()), "&filetype") == "netrw"|q|endif
augroup END

set pastetoggle=<F2>

set laststatus=1

set title

autocmd FileType go setlocal noexpandtab
autocmd FileType gitconfig setlocal noexpandtab

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fsSLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugins')

Plug 'chriskempson/base16-vim'
if executable('go')
  Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }
endif

call plug#end()

if executable('go')
  let g:go_fmt_command='goimports'
  let g:go_auto_type_info=1
  set completeopt-=preview
endif

set termguicolors
colorscheme base16-tomorrow-night
