#!/bin/bash

set -e

[[ -z "$DEBUG" ]] || set -x

no_color='\033[0m'

info() {
  local yellow_color='\033[0;33m'
  echo -e "${yellow_color}"$@"${no_color}"
}

error() {
  local red_color='\033[0;31m'
  echo -e "${red_color}"$@"${no_color}"
  exit 1
}

# Create a .netrc file with needed permissions.
[[ ! -f "$HOME/.netrc" ]] && {
  info "==> Creating .netrc file..."
  touch "$HOME/.netrc"
  chmod 600 "$HOME/.netrc"
}

# Generate an SSH key.
[[ ! -f "$HOME/.ssh/key" ]] && {
  info "==> Generating SSH key..."
  ssh-keygen -t ed25519 -C "$(hostname)" -q -N "" -f ~/.ssh/key
}
