#!/usr/bin/env bash

umask 077
set -euo pipefail
cd "$(dirname $0)/.."

[[ ${DEBUG:-0} == "1" ]] &&
  set -x

DOTFILES="${DOTFILES:-$HOME/src/dotfiles}"

BLUE="\033[0;34m"
NO_COLOR="\033[0m"
RED="\033[0;31m"

info() {
  printf "$BLUE${1:-}$NO_COLOR\n"
}

error() {
  printf "$RED${1:-}$NO_COLOR\n"
  exit 1
}

[[ "${BASH_VERSINFO[0]}" -lt 4 ]] &&
  error "bash >=4 is required."

main() {
  local platform="$(uname -s)"

  [[ "$platform" == CYGWIN* ]] || [[ "$platform" == MINGW* ]] && {
    info "You're running Windows. Proceeding with caution."

    [[ "$platform" == CYGWIN* ]] && [[ ! "${CYGWIN:-}" == "winsymlinks:nativestrict" ]] &&
      error 'Set CYGWIN environment variable to `winsymlinks:nativestrict` in Windows settings and try again.'
    [[ "$platform" == MINGW* ]] && [[ ! "${MSYS:-}" == "winsymlinks:nativestrict" ]] &&
      error 'Set MSYS environment variable to `winsymlinks:nativestrict` in Windows settings and try again.'

    set +e
    net session >/dev/null 2>&1
    [[ ! $? -eq 0 ]] && error "Admin rights is required to install dotfiles on Windows."
    set -e
  }

  info "Installing dotfiles..."

  ln -sf "$DOTFILES/bashrc" "$HOME/.bashrc"
  ln -sf "$DOTFILES/profile" "$HOME/.profile"

  [[ ! -d "$HOME/.vim" ]] && mkdir -p "$HOME/.vim"
  ln -sf "$DOTFILES/vimrc" "$HOME/.vim/vimrc"

  [[ ! -d "$HOME/.config/git" ]] && mkdir -p "$HOME/.config/git"
  ln -sf "$DOTFILES/config/git/config" "$HOME/.config/git/config"

  if [[ "$platform" == CYGWIN* ]] || [[ "$platform" == MINGW* ]]; then
    ln -sf "$DOTFILES/platform/windows/gitconfig" "$HOME/.config/git/config.platform"
    ln -sf "$DOTFILES/minttyrc" "$HOME/.minttyrc"
  else
    ln -sf "$DOTFILES/platform/other/gitconfig" "$HOME/.config/git/config.platform"
  fi

  [[ "$(uname -o)" == "Android" ]] && {
    symlink hushlogin

    [[ ! "$(readlink "$HOME/.termux")" == "$DOTFILES/platform/termux" ]] && {
      ln -sf "$DOTFILES/platform/termux" "$HOME/.termux"
    }
  }
}

main "$@"
