name: Lint
on:
  push:
    branches: [master]
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.4
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: Cache dependencies and build cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - name: Run shfmt
        run: shfmt -d .
